---
name: test module
on: pull_request
jobs:
  setup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout a private repository
      pull-requests: write # For ci-info and github-comment
    outputs:
      modules: ${{ steps.list-targets.outputs.modules }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.53.1
      - uses: suzuki-shunsuke/tfaction/list-targets@pr/2747
        id: list-targets

  test-module:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: {}
    name: "test-module (${{matrix.target}})"
    needs: setup
    # if services is empty, the build job is skipped
    if: "join(fromJSON(needs.setup.outputs.modules), '') != ''"
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(needs.setup.outputs.modules)}}
    env:
      TFACTION_WORKING_DIR: ${{matrix.target}}
      TFACTION_TARGET: module
      TFACTION_JOB_TYPE: terraform
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Generate token
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{vars.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          # pull_requests:write - Post comments
          # contents:write - Push commits
          permissions: >-
            {
              "pull_requests": "write",
              "contents": "write"
            }
          repositories: >-
            ["${{github.event.repository.name}}"]

      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.55.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: suzuki-shunsuke/tfaction/install@latest
      - name: Test Module
        uses: suzuki-shunsuke/tfaction/test-module@latest
        with:
          github_token: ${{steps.token.outputs.token}}
